services:
  service:
    build: ./service
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/myapp?sslmode=disable
    depends_on:
      - db
    restart: always

  ui:
    build: ./ui
    ports:
      - "3000:3000"
    restart: always
  
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - ./service/db/init:/docker-entrypoint-initdb.d/
    restart: on-failure
  
  redis:
    container_name: "redis"
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: on-failure
